source 'https://rubygems.org'

gem 'rails', '3.2.5'

group :development do
	gem 'sqlite3', '1.3.5'
	gem 'rspec-rails', '2.10.0'
	gem 'annotate', ">=2.5.0.pre1"
end

group :test do 
	gem 'webrat'
	gem 'rspec', '2.10.0'
end

gem 'jquery-rails'